
- name: Copy over virtual network definition files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/tmp"
    owner: root
    group: root
    mode: 0644
  loop:
    - ocp4-net.xml
    - ocp4-prov-net.xml

- name: Check if ocp4-net network is already configured
  ansible.builtin.command: virsh net-dumpxml ocp4-net
  register: ocp4_net_return
  failed_when: ocp4_net_return.rc > 1

- name: Enable OpenShift base network (192.168.123.100/24)
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "virsh net-define /tmp/ocp4-net.xml"
    - "virsh net-start ocp4-net"
    - "virsh net-autostart ocp4-net"
  when: ocp4_net_return.rc == 1

- name: Install required base packages
  dnf:
    name:
      - python3-virtualenv
    state: latest
  become: True

- name: Get a list of current VM definitions
  virt:
    command: list_vms
  register: vm_list

- name: Check if base RHEL/CentOS 8 already disk image exists
  stat:
    path: /var/lib/libvirt/images/centos8-kvm.qcow2
  register: base_result

- name: Downloading CentOS 8 base image
  ansible.builtin.get_url:
    url: https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2
    dest: /var/lib/libvirt/images/centos8-kvm.qcow2
    mode: 0644
  when: not base_result.stat.exists

- name: Copy over ifcfg-eth0 for bastion VM
  ansible.builtin.copy:
    src: "ifcfg-eth0"
    dest: "/tmp"
    owner: root
    group: root
    mode: 0644

- name: Check if Bastion disk image already exists - don't clobber
  stat:
    path: /var/lib/libvirt/images/ocp4-bastion.qcow2
  register: bastion_result

- name: Creating and customising Bastion VM image from CentOS 8 template
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "qemu-img create -f qcow2 /var/lib/libvirt/images/ocp4-bastion.qcow2 -b /var/lib/libvirt/images/centos8-kvm.qcow2 -F qcow2 200G"
    - "virt-customize -a /var/lib/libvirt/images/ocp4-bastion.qcow2 --uninstall cloud-init"
    - "virt-customize -a /var/lib/libvirt/images/ocp4-bastion.qcow2 --root-password password:redhat"
    - "virt-copy-in -a /var/lib/libvirt/images/ocp4-bastion.qcow2 /tmp/ifcfg-eth0 /etc/sysconfig/network-scripts"
    - "virt-customize -a /var/lib/libvirt/images/ocp4-bastion.qcow2 --run-command \"mkdir -p /root/.ssh/ && chmod -R 0700 /root/.ssh/\""
    - "virt-customize -a /var/lib/libvirt/images/ocp4-bastion.qcow2 --run-command \"restorecon -Rv /root/.ssh/\""
  when: not bastion_result.stat.exists

- name: Check if Bastion is defined
  ansible.builtin.command: virsh dumpxml ocp4-bastion
  register: bastion_defined
  failed_when: bastion_defined.rc > 1

- name: Build Bastion VM definition for SNO ISO Install
  ansible.builtin.command: >
    virt-install --virt-type kvm --ram {{ vms.bastion.mem }} --vcpus {{ vms.bastion.cpus }} --cpu=host-passthrough --os-variant rhel8.1
    --disk path=/var/lib/libvirt/images/ocp4-bastion.qcow2,device=disk,bus=virtio,format=qcow2
    --network network:ocp4-net,mac={{ vms.bastion.base_network }}
    --boot hd --noautoconsole --vnc --name ocp4-bastion --noreboot
  when:
    - bastion_defined.rc == 1
    - deploy_type == "sno-iso"

- name: Check if firewalld is available
  ansible.builtin.command: systemctl status firewalld
  register: firewalld_avail
  failed_when: firewalld_avail.rc == 1

- name: Enable firewalld for IPI deployments
  ansible.builtin.systemd:
    name: firewalld
    enabled: yes
    state: started
  when:
    - firewalld_avail.rc < 4

- name: Enable firewalld ports for IPI deployments
  firewalld:
    port: 6230-6236/udp
    zone: libvirt
    permanent: yes
    state: enabled
  when:
    - firewalld_avail.rc !=	4

- name: Enable port 9001 forwarding to bastion:9001 with firewalld
  firewalld:
    port_forward:
      port: "9001"
      proto: tcp
      toaddr: 192.168.123.100
      toport: "9001"
    zone: public
    permanent: yes
    state: enabled
  when:
    - firewalld_avail.rc != 4

- name: Enable port 8000 forwarding to bastion:22 with firewalld
  firewalld:
    port_forward:
      port: "8000"
      proto: tcp
      toaddr: 192.168.123.100
      toport: "22"
    zone: public
    permanent: yes
    state: enabled
  when:
    - firewalld_avail.rc != 4

- name: Iptables flush libvirt forward filter
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: yes
  with_items:  [ 'LIBVIRT_FWO', 'LIBVIRT_FWI' ]
  when:
    - firewalld_avail.rc == 4

- name: Enable iptables ports for IPI deployments
  ansible.builtin.iptables:
    chain: LIBVIRT_INP
    protocol: udp
    destination_port: "6230:6236"
    jump: ACCEPT
  when:
    - firewalld_avail.rc == 4

- name: Enable port 9001 on host with iptables
  ansible.builtin.iptables:
    chain: FORWARD
    protocol: tcp
    action: insert
    rule_num: "1"
    destination_port: "9001"
    jump: ACCEPT
  when: firewalld_avail.rc == 4

- name: Forward port 9001 to bastion:9001 with iptables
  ansible.builtin.iptables:
    action: insert
    rule_num: "1"
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: "9001"
    jump: DNAT
    to_destination: 192.168.123.100:9001
  when: firewalld_avail.rc == 4   

- name: Enable port 8000 on host with iptables
  ansible.builtin.iptables:
    chain: FORWARD
    protocol: tcp
    action: insert
    rule_num: "1"
    destination_port: "8000"
    jump: ACCEPT
  when: firewalld_avail.rc == 4

- name: Forward port 8000 to bastion:22 with iptables
  ansible.builtin.iptables:
    action: insert
    rule_num: "1"
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: "8000"
    jump: DNAT
    to_destination: 192.168.123.100:22
  when: firewalld_avail.rc == 4   

- name: Check if ssh-key already exists
  ansible.builtin.stat:
    path: "/root/.ssh/id_rsa"
  register: root_ssh_key

- name: Generate ssh-key for connectivity across deployments
  openssh_keypair:
    path: "/root/.ssh/id_rsa"
    type: rsa
    size: 4096
    state: present
    force: no
  when: not root_ssh_key.stat.exists

- name: Make lab directory
  ansible.builtin.file:
    path: /root/lab
    state: directory

- name: Make sno directory 
  ansible.builtin.file:
    path: /root/sno-{{ item }}
    state: directory
  loop:
    - rhacm
    - edge1
    - edge2

- name: Make sno image directory 
  ansible.builtin.file:
    path: /var/lib/libvirt/images/sno-{{ item }}
    state: directory
    owner: qemu
    group: qemu
  loop:
    - rhacm
    - edge1
    - edge2

- name: Download OpenShift Client
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-client-linux.tar.gz
    dest: /root
    mode: 0644

- name: Download OpenShift Installer
  ansible.builtin.get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_version }}/openshift-install-linux.tar.gz
    dest: /root
    mode: 0644

- name: Unpack OpenShift Client & Installer
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ item }}"
    dest: /usr/bin
  loop:
    - "/root/openshift-install-linux.tar.gz"
    - "/root/openshift-client-linux.tar.gz"

- name: Remove OpenShift client and installer tarballs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/root/openshift-install-linux.tar.gz"
    - "/root/openshift-client-linux.tar.gz"

- name: Set DNS Server to bastion host
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    insertbefore: '^nameserver.*'
    line: "nameserver 192.168.123.100"
    firstmatch: yes