- src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_base_software.git
  scm: git
  name: base_software
  version: v0.0.10

- name: base_virt
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_base_virt.git
  scm: git
  version: v0.1.5

- name: prepare_bastion
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_prepare_bastion.git
  scm: git
  version: v0.0.4

- name: disconnected_registry
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_disconnected_registry.git
  scm: git

- name: ocp4_role_acm
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_acm.git
  scm: git
  version: v0.0.1

- name: ocp4_role_acs
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_acs.git
  scm: git
  version: v0.0.1

- name: ocp4_role_cnv
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_cnv.git
  scm: git
  version: v0.0.1

- name: ocp4_role_imgreg
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_imgreg.git
  scm: git
  version: v0.0.3

- name: ocp4_role_nfsmount
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_nfsmount.git
  scm: git
  version: v0.0.3

- name: deploy_bastion
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_bastion.git
  scm: git
  version: v0.0.12

- name: deploy_guac
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_guacamole.git
  scm: git
  version: v0.0.2

- name: deploy_ocp
  src: https://github.com/RHFieldProductManagement/ocp4_aio_infra_role_deploy_ocp.git
  scm: git
  version: v0.0.7

- name: ocp4_role_ocs
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_ocs.git
  scm: git
  version: v0.0.8

- name: ocp4_role_deploy_cnvlab
  src: https://github.com/RHFieldProductManagement/ocp4_aio_role_deploy_cnvlab.git
  scm: git
  version: v0.0.16
