---
# vim: set ft=ansible:

- name: Reload inventory for bastion host
  gather_facts: false
  hosts: bastion
  tasks:

    - name: Set fact for OCP deployment if requesting dependents
      set_fact:
        deploy_ocp: true
      when: ocp4_aio_deploy_ocs or ocp4_aio_deploy_cnv or ocp4_aio_deploy_acm

    - name: Set facts for variants if requesting OCP Plus
      set_fact:
        ocp4_aio_deploy_ocp: true
        ocp4_aio_deploy_acm: true
        ocp4_aio_deploy_acs: true
      when: ocp4_aio_deploy_ocp_plus

    - name: Print Deployment Complete
      debug:
        msg: "OpenShift AIO: Deployment has been Successful!"

    - name: Print Deployment Specifics
      vars:
        msg: |
           OpenShift Version: {{ ocp4_aio_ocp_version }}
           Baremetal Provider: {{ baremetal_provider }}
           Baremetal Server: {{ groups['target'][0] }}
           Deployment Type: {{ ocp4_aio_deploy_type }}
           Compact Deployment: {{ ocp4_aio_deploy_compact }}
           Deploy CNV: {{ ocp4_aio_deploy_cnv }}
           Deploy OCS: {{ ocp4_aio_deploy_ocs }}
           Deploy ACM: {{ ocp4_aio_deploy_acm }}
           Deploy ACS: {{ ocp4_aio_deploy_acs }}
      debug:
        msg: "{{ msg.split('\n') }}"

    - name: Print Base Information
      vars:
        msg: |
          To get started, you'll first need to connect to your {{ baremetal_provider }} system.
          - Open a shell session to this machine: `ssh root@{{ groups['target'][0] }}`
          - All tasks should then be performed on the bastion machine, hop to this: `ssh root@192.168.123.100`.
          - Here you'll find all of the tools you'll likely need, feel free to install more.
          - root password for the bastion host is {{ hostvars['passwd_holder']['root_password'] }}
      debug:
        msg: "{{ msg.split('\n') }}"

    - name: Print Kube Configuration
      vars:
        msg: |
          As you've requested OpenShift to be installed, you can access the console either via proxy or Guacamole (if enabled).
          To access the environment via a Squid Proxy, setup the following SOCKS proxy:

          {{ groups['target'][0] }}:3128

          Then enable DNS over SOCKS

          The console is available at: https://console-openshift-console.apps.aio.example.com
          The kubeadmin password is: {{ hostvars['kube_holder']['kubeadmin_password'] }}

          If you'd like CLI access, the bastion host will have already been setup - `ssh root@192.168.123.100`
          You should then automatically have oc/kubectl access to the cluster. Check out ~/ocp-install/auth/.
      debug:
        msg: "{{ msg.split('\n') }}"
      when:
        - not ocp4_aio_use_ddns 
        - ocp4_aio_deploy_ocp

    - name: Print Kube Configuration
      vars:
        msg: |
          As you've requested OpenShift to be installed, you can access the console either via proxy or Guacamole (if enabled).
          To access the environment via a Squid Proxy, setup the following SOCKS proxy:

          proxy.{{ guid }}.{{ cluster_dns_zone }}:3128

          and enable DNS over SOCKS

          The console is available at: https://console-openshift-console.apps.{{ guid }}.{{ cluster_dns_zone }}
          The kubeadmin password is: {{ hostvars['kube_holder']['kubeadmin_password'] }}

          If you'd like CLI access, the bastion host will have already been setup - `ssh root@192.168.123.100`
          You should then automatically have oc/kubectl access to the cluster. Check out ~/ocp-install/auth/.
      debug:
        msg: "{{ msg.split('\n') }}"
      when:
        - ocp4_aio_use_ddns 
        - ocp4_aio_deploy_ocp

    - name: Print Guacamole Information
      vars:
        msg: |
          As you've enabled Guacamole support, you can access everything you need without a proxy.
          To access the environment via your web-browser only (Guacamole)

          Use this URL: http://{{ groups['target'][0] }}:8080/guacamole
          Username: guacadmin
          Password: {{ hostvars['guac_holder']['guac_shared_password'] }}

          The 'Lab Desktop' will give you a GNOME desktop environment, and 'Bastion SSH' just CLI access.
      debug:
        msg: "{{ msg.split('\n') }}"
      when: ocp4_aio_deploy_guacamole
