---
# vim: set ft=ansible:

# Step 0: Configure facts based on vars selection
- name: Set fact for OCP deployment if requesting dependents
  hosts: localhost
  tasks:
    - name: Get facts playbook
      include_tasks: set_facts.yml

# Step 1: Deploy Base Infrastructure on provider
- import_playbook: "./{{ baremetal_provider }}/base_infra.yml"

# Step 2: Create inventory
- hosts: localhost
  roles:
    - create_inventory

# Step 3 : Prepare Base Host
- hosts: target
  gather_facts: true
  tasks:
    - name: Setup base software
      include_role:
        name: base_software
      vars: 
        ocp4_aio_baremetal_provider: "{{ baremetal_provider }}"

    - name: Setup base virt
      include_role:
        name: base_virt

    - name: Prepare bastion VM
      include_role:
        name: prepare_bastion

    - name: deploy Guacamole
      include_role:
        name: deploy_guac
      when: ocp4_aio_deploy_guacamole

# Step 4 : Prepare Bastion VM 
- hosts: bastion
  roles:
    - deploy_bastion

  tasks:
# Step 5 : Deploy Openshift or SNO
    - name: deploy OCP
      include_role:
        name: deploy_ocp
      vars:
        aio_host_ip_address: "{{ groups['target'][0] }}"
      when: ocp4_aio_deploy_type == 'upi' or ocp4_aio_deploy_type == 'ipi'

- hosts: target
  tasks:
    - name: Deploy SNO
      include_role:
        name: deploy_ocp
      when: ocp4_aio_deploy_type == "sno"

# Step 5 : Get infos from deployments
- hosts: localhost
  roles:
    - generate_configs

# Step 6 : Deploy operators on OCP
- hosts: bastion
  tasks:

    - name: Setting up OCS Storage
      include_role:
        name: ocp4_role_ocs
      when: ocp4_aio_deploy_ocs 

    - name: Setting up NFS Storage
      include_role: 
        name: ocp4_role_nfsmount
      when: not ocp4_aio_deploy_ocs

    - name: Installing ACM
      include_role:
        name: ocp4_role_acm
      when: ocp4_aio_deploy_acm or ocp4_aio_deploy_ocp_plus or ocp4_aio_deploy_sno

    - name: Installing ACS
      include_role:
        name: ocp4_role_acs
      when: ocp4_aio_deploy_acs or ocp4_aio_deploy_ocp_plus or ocp4_aio_deploy_sno

    - name: Installing CNV
      include_role:
        name: ocp4_role_cnv
      when: ocp4_aio_deploy_cnv

    - name: Deploy internal registry
      include_role:
        name: ocp4_role_imgreg
  
# Step 7: Print Output to User
- import_playbook: finish.yml
  when: not ocp4_aio_deploy_sno | bool

# Step 7-SNO: Print Output to User
- import_playbook: finish_sno.yml
  when: ocp4_aio_deploy_sno