---
# vim: set ft=ansible:

# Step 0: Configure facts based on vars selection
- name: Set fact for OCP deployment if requesting dependents
  hosts: localhost
  tasks:
    - name: Get facts playbook
      include_tasks: set_facts.yml

# Step 1: Deploy Base Infrastructure on provider
- import_playbook: "./{{ baremetal_provider }}/base_infra.yml"

# Step 2: Deploy Base Software Configuration
- import_playbook: base_software.yml

# Step 3: Deploy Base Virtualisation Configuration
- import_playbook: base_virt.yml

# Step 4: Deploy Bastion VM for supporting services
- import_playbook: deploy_bastion.yml

- import_playbook: deploy_guac.yml
  when: deploy_guacamole

# Step 5: Deploy the OpenShift cluster if requested
- import_playbook: deploy_cluster.yml
  when: deploy_ocp

# Step 6: Deploy OpenShift Container Storage
- import_playbook: deploy_ocs.yml
  when: deploy_ocs

# Step 7: Deploy NFS Storage (when OCS not used)
- import_playbook: deploy_nfs.yml
  when: deploy_nfs

# Step 8: Deploy OpenShift Virtualization
- import_playbook: deploy_cnv.yml
  when: deploy_cnv

# Step 9: Deploy Advanced Cluster Manager
- import_playbook: deploy_acm.yml
  when: deploy_acm

# Step 10: Deploy Advanced Cluster Security
- import_playbook: deploy_acs.yml
  when: deploy_acs

# Step 11: Print Output to User
- import_playbook: finish.yml
