---
# vim: set ft=ansible:

# Step 0: Deploy Base Infrastructure
- import_playbook: "./{{ baremetal_provider }}/base_infra.yml"
#- import_playbook: test.yml
- import_playbook: base_software.yml
- import_playbook: base_virt.yml
- import_playbook: deploy_bastion.yml

- import_playbook: deploy_cluster.yml
  when: deploy_ocp

- import_playbook: deploy_ocs.yml
  when: deploy_ocs
# Step 2: Deploy Variant Pre-Infra
#- import_playbook: "./{{ variant_type }}/pre_infra.yml"

# Step 3: Deploy Variant Main
#- import_playbook: "./{{ variant_type }}/infra.yml"

# Step 4: Deploy Variant Post-Infra
#- import_playbook: "./{{ variant_type }}/post_infra.yml"

# Step 5: Completion Callback
#- import_playbook: completion_callback.yml
