---
# vim: set ft=ansible:

# Step 0: Configure facts based on vars selection
- name: Set fact for OCP deployment if requesting dependents
  hosts: localhost
  tasks:
    - name: Get facts playbook
      include_tasks: set_facts.yml

# Step 1: Deploy Base Infrastructure on provider
- import_playbook: "./{{ baremetal_provider }}/base_infra.yml"

# Step 2: Create inventory
- hosts: localhost
  roles:
    - create_inventory

# Step 3 : Prepare Base Host
- hosts: target
  roles:
    - base_software
    - base_virt
    - prepare_bastion

# Step 4 : Prepare Bastion VM 
- hosts: bastion
  roles:
    - deploy_bastion
  tasks:
    - name: deploy Guacamole
      include_role:
        name: deploy_guac
      when: deploy_guacamole

# Step 5 : Deploy Openshift or SNO
    - name: deploy OCP
      include_role:
        name: deploy_ocp
      when: deploy_type == 'upi' or deploy_type == 'ipi'

- hosts: target
  tasks:
    - name: Deploy SNO
      include_role:
        name: deploy_ocp
      when: deploy_type == "sno-iso"

# Step 5 : Get infos from deployments
- hosts: localhost
  roles:
    - generate_configs

# Step 6 : Deploy operators on OCP
- hosts: bastion
  tasks:

    - name: Setting up OCS Storage
      include_role:
        name: ocp4_role_ocs
      when: deploy_ocs 

    - name: Setting up NFS Storage
      include_role: 
        name: ocp4_role_nfsmount
      when: not deploy_ocs

    - name: Installing ACM
      include_role:
        name: ocp4_role_acm
      when: deploy_acm or deploy_ocp_plus or deploy_sno

    - name: Installing ACS
      include_role:
        name: ocp4_role_acs
      when: deploy_acs or deploy_ocp_plus or deploy_sno

    - name: Installing CNV
      include_role:
        name: ocp4_role_cnv
      when: deploy_cnv

    - name: Deploy internal registry
      include_role:
        name: ocp4_role_imgreg
  
# Step 7: Print Output to User
- import_playbook: finish.yml
  when: not deploy_sno | bool

# Step 7-SNO: Print Output to User
- import_playbook: finish_sno.yml
  when: deploy_sno