---
# vim: set ft=ansible:

# Step 0: Deploy Base Infrastructure
- import_playbook: "./{{ baremetal_provider }}/base_infra.yml"

# Step 1: Deploy Base Software
#- import_playbook: base_software.yml

# Step 2: Deploy Variant Pre-Infra
#- import_playbook: "./{{ variant_type }}/pre_infra.yml"

# Step 3: Deploy Variant Main
#- import_playbook: "./{{ variant_type }}/infra.yml"

# Step 4: Deploy Variant Post-Infra
#- import_playbook: "./{{ variant_type }}/post_infra.yml"

# Step 5: Completion Callback
#- import_playbook: completion_callback.yml
