
- name: Set fact for OCP deployment if requesting dependents
  set_fact:
    override_deploy_ocp: true
  when: deploy_ocs or deploy_cnv or deploy_acm

- name: Set a placeholder for override_deploy_compact
  set_fact:
    override_deploy_compact: false

- name: Force compact mode when ocp_workers is 0
  set_fact:
    override_deploy_compact: true
  when: ocp_workers == 0

- name: Set a placeholder for override_deploy_nfs
  set_fact:
    override_deploy_nfs: false

- name: Enable NFS storage when OCS is disabled
  set_fact:
    override_deploy_nfs: true
  when: not deploy_ocs
