
- name: Set fact for OCP deployment if requesting dependents
  set_fact:
    override_deploy_ocp: true
  when: deploy_ocs or deploy_cnv or deploy_acm

- name: Enable NFS storage when OCS is disabled
  set_fact:
    override_deploy_nfs: true
  when: not deploy_ocs
