- name: Install common base packages
  import_tasks: common.yml

- name: Install software for IPI deployments
  import_tasks: base_software_ipi.yml
  when: deploy_type == 'ipi' or deploy_sno

- name: Install software for SNO
  import_tasks: base_software_sno.yml
  when: deploy_type == 'sno-ipi'
